project:
  type: website
  output-dir: docs
execute:
  python: /Users/marcusprewarski/projects/venv/bin/python
editor: 
  render-on-save: true

website:
  title: "Marcus Prewarski"
  navbar:
    search: true
    right:
      - about.qmd
      - text: "Home"
        href: index.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css
